#!/usr/bin/env python3
"""Emit descriptors from ../descriptors.h as a standalone C header.

    gen_desc.py <descriptors.h> <out.h> <c_name>=<prefix> [...]

Each pair yields `<prefix>_desc` and `<PREFIX>_DESC_LEN`, one header per target
holding only its own descriptors, so nothing lands in a binary that does not use it,
and the length of every input report the descriptor declares: `<PREFIX>_INPUT_<ID>_LEN`
in bytes after the ID, `<prefix>_input_len(id)` to look one up, and
`<PREFIX>_FIRST_INPUT_ID`. GET_REPORT answers from these, and the rigs assert the
lengths they send against them, so a hand-kept length cannot drift from the bytes.
Generating at build time rather than checking in a second copy keeps the emulator
byte-for-byte with what the harness tests against; otherwise a hardware run proves
nothing about the host results.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir, "tools"))
import hiditems  # noqa: E402


def normalise_end_collection(data):
    """Rewrite End Collection items that carry a data byte.

    Every Gameball descriptor in the corpus encodes it as 0xC1 0x00, bSize 1 where the
    HID spec says 0: tolerant parsers skip it by size, a strict one reads the trailing
    0x00 as an undefined Main item. The well formed 0xC0 tells the two apart on hardware.
    """
    out, fixed = [], 0
    for item in hiditems.walk_items(data):
        if item.tag == 0xC0 and item.size:
            out.append(0xC0)
            fixed += 1
        else:
            out.extend(data[item.offset:item.end])
    return out, fixed


def signed(value, size):
    """A short item's data as the signed number HID reads it as."""
    bits = 8 * size
    return value - (1 << bits) if size and value >= 1 << (bits - 1) else value


def logical_minimum(value):
    """The shortest Logical Minimum item that holds value."""
    for prefix, size in ((0x15, 1), (0x16, 2), (0x17, 4)):
        if -(1 << (8 * size - 1)) <= value < 1 << (8 * size - 1):
            return [prefix] + list((value & ((1 << (8 * size)) - 1)).to_bytes(size, "little"))
    raise ValueError(value)


def fix_signed_axes(data):
    """Give relative axes a negative Logical Minimum.

    The Gameball descriptors never set one for X, Y, wheel or pan, so the 0 left over
    from the button block stands and the axes read as unsigned 0..127; a parser that
    honours that discards every negative delta and the pointer can only travel right
    and down. deskhop reads the field as signed regardless; Windows does not. Inserts
    Logical Minimum -127 before the first relative Input item that needs it, a global
    item, so every axis after it inherits the fix.
    """
    out, fixed, lmin, lmax = [], 0, None, None
    for item in hiditems.walk_items(data):
        tag, val = item.tag, item.value

        if tag == 0x14:
            lmin = signed(val, item.size)
        if tag == 0x24:
            lmax = signed(val, item.size)
        if tag == 0x80 and (val & 0x04) and lmin == 0 and lmax and lmax > 0 and not fixed:
            out.extend(logical_minimum(-lmax))
            lmin = -lmax
            fixed += 1

        out.extend(data[item.offset:item.end])
    return out, fixed


def input_reports(data):
    """Bytes per input report, keyed by report ID (0 where the descriptor declares none),
    in the order the IDs first carry an Input item. Report Size, Report Count and
    Report ID are globals, so Push and Pop are followed too."""
    size = count = rid = 0
    stack, bits = [], {}
    for item in hiditems.walk_items(data):
        if item.tag == 0x74:
            size = item.value
        elif item.tag == 0x94:
            count = item.value
        elif item.tag == 0x84:
            rid = item.value
        elif item.tag == 0xA4:
            stack.append((size, count, rid))
        elif item.tag == 0xB4 and stack:
            size, count, rid = stack.pop()
        elif item.tag == 0x80:
            bits[rid] = bits.get(rid, 0) + size * count
    return {rid: (b + 7) // 8 for rid, b in bits.items()}


def extract(corpus, name):
    data = corpus.get(name)
    if data is None:
        sys.exit("gen_desc.py: %s not found" % name)
    if not data:
        sys.exit("gen_desc.py: %s parsed to zero bytes" % name)
    return data


def main():
    flags = {"--normalise-end-collection", "--fix-signed-axes"}
    given = {a for a in sys.argv[1:] if a in flags}
    argv = [a for a in sys.argv[1:] if a not in flags]
    normalise = "--normalise-end-collection" in given
    fix_axes = "--fix-signed-axes" in given
    if len(argv) < 2:
        sys.exit(__doc__)
    src, out, pairs = argv[0], argv[1], argv[2:]
    if not pairs:
        sys.exit("gen_desc.py: no <c_name>=<prefix> pairs given")

    corpus = hiditems.read_corpus(open(src).read())
    lines = ["/* Generated by emu/gen_desc.py from %s - do not edit. */" % src,
             "#pragma once",
             "#include <stdint.h>",
             ""]
    summary = []

    for pair in pairs:
        name, _, prefix = pair.partition("=")
        if not prefix:
            sys.exit("gen_desc.py: expected <c_name>=<prefix>, got %r" % pair)

        data = extract(corpus, name)
        if normalise:
            data, fixed = normalise_end_collection(data)
            if fixed:
                print("gen_desc.py: %s, rewrote %d End Collection item(s)" % (prefix, fixed))
        if fix_axes:
            data, fixed = fix_signed_axes(data)
            if fixed:
                print("gen_desc.py: %s, gave the relative axes a signed range" % prefix)
        macro = prefix.upper() + "_DESC_LEN"

        lines.append("#define %s %d" % (macro, len(data)))
        lines.append("static const uint8_t %s_desc[%s] = {" % (prefix, macro))
        for i in range(0, len(data), 12):
            lines.append("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
        lines.append("};")
        lines.append("")

        inputs = input_reports(data)
        if not inputs:
            sys.exit("gen_desc.py: %s declares no input report" % name)
        up = prefix.upper()
        for rid, n in inputs.items():
            lines.append("#define %s_INPUT_%02X_LEN %d" % (up, rid, n))
        lines.append("#define %s_FIRST_INPUT_ID 0x%02X" % (up, next(iter(inputs))))
        lines.append("static inline uint16_t %s_input_len(uint8_t id) {" % prefix)
        lines.append("    switch (id) {")
        for rid in inputs:
            lines.append("    case 0x%02X: return %s_INPUT_%02X_LEN;" % (rid, up, rid))
        lines.append("    default: return 0;")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        summary.append("%s %d" % (prefix, len(data)))

    open(out, "w").write("\n".join(lines) + "\n")
    print("gen_desc.py: " + ", ".join(summary) + " bytes")


if __name__ == "__main__":
    main()
