#!/usr/bin/env python3
"""Emit one descriptor from ../descriptors.h as a standalone C array.

The emulator must present the byte-for-byte descriptor the harness tests
against, otherwise a hardware run proves nothing about the host results.
Generating it at build time rather than checking in a second copy is what
keeps the two from drifting apart.
"""
import re
import sys

def main():
    src, name, out = sys.argv[1], sys.argv[2], sys.argv[3]
    text = open(src).read()
    m = re.search(r'static const uint8_t %s\[\]\s*=\s*\{(.*?)\};' % re.escape(name),
                  text, re.S)
    if not m:
        sys.exit("gen_desc.py: %s not found in %s" % (name, src))

    body = re.sub(r'/\*.*?\*/', '', m.group(1), flags=re.S)
    body = re.sub(r'//[^\n]*', '', body)
    data = [int(b, 16) for b in re.findall(r'0[xX]([0-9A-Fa-f]{1,2})', body)]
    if not data:
        sys.exit("gen_desc.py: %s parsed to zero bytes" % name)

    lines = ["/* Generated by emu/gen_desc.py from %s - do not edit. */" % src,
             "#pragma once",
             "#include <stdint.h>",
             "",
             "#define BITDO_DESC_LEN %d" % len(data),
             "",
             "static const uint8_t bitdo_report_desc[BITDO_DESC_LEN] = {"]
    for i in range(0, len(data), 12):
        lines.append("    " + " ".join("0x%02X," % b for b in data[i:i + 12]))
    lines.append("};")
    open(out, "w").write("\n".join(lines) + "\n")
    print("gen_desc.py: %s -> %d bytes" % (name, len(data)))

main()
