#!/usr/bin/env python3
"""Lift named functions verbatim out of a deskhop source file.

The point is that the harness runs the firmware's own code rather than a hand
copy, so a test can never quietly drift from what the device actually does.

    lift.py <source.c> <out.c> func1 [func2 ...]

Fails loudly if a function is not found, so a rename upstream breaks the build
instead of silently testing nothing.
"""
import re
import sys


IDENT = re.compile(r"\w")

# The bodies below are copied verbatim out of DeskHop, which is GPLv3. The file
# this tool writes is therefore a derivative work and carries the same terms;
# saying so in the generated file keeps that visible to anyone who reads it out
# of the build directory without the repo around it.
NOTICE = """   The function bodies below are copied verbatim from DeskHop
   (https://github.com/hrvach/deskhop), Copyright (c) 2025 Hrvoje Cavrak,
   licensed under the GNU General Public License version 3. This generated file
   is a derivative work and is covered by the same licence; see LICENSE.
"""


def matching_paren(src, open_idx):
    """Index of the ) closing the ( at open_idx, or -1. Counts depth, so a
    parameter list carrying a function pointer does not end the search early."""
    depth = 0
    for k in range(open_idx, len(src)):
        if src[k] == "(":
            depth += 1
        elif src[k] == ")":
            depth -= 1
            if depth == 0:
                return k
    return -1


def extract(src, name):
    """Return the full text of a function definition, brace matched."""
    needle = name + "("
    pos = 0
    rejected = []
    while True:
        i = src.find(needle, pos)
        if i == -1:
            raise SystemExit(
                "lift.py: no definition of %s found in this file.\n"
                "  %d call-like occurrence(s) were skipped:%s\n"
                "  If it was renamed upstream, update the Makefile rule that names it."
                % (name, len(rejected),
                   "".join("\n    line %d: %s" % (n, t) for n, t in rejected) or " none"))

        pos = i + len(needle)

        # `get_keyboard` inside `my_get_keyboard(` is a different function
        if i > 0 and IDENT.match(src[i - 1]):
            continue

        line_start = src.rfind("\n", 0, i) + 1
        brace = src.find("{", i)
        semi = src.find(";", i)

        if brace == -1 or (semi != -1 and semi < brace):
            continue    # a prototype, or a call ending in a semicolon

        # A definition has only the parameter list between the name and the body.
        # A call in a condition - `if (!get_keyboard(iface, id)) {` - also puts a
        # brace before any semicolon, and lifting from there would take the
        # caller's body instead. Requiring the gap between the closing paren and
        # the brace to be blank is what separates the two.
        close = matching_paren(src, i + len(needle) - 1)
        if close == -1 or close > brace or src[close + 1:brace].strip():
            rejected.append((src.count("\n", 0, i) + 1, src[line_start:src.find("\n", i)].strip()))
            continue

        break

    depth, k = 0, brace
    while True:
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return src[line_start:k + 1]


def main():
    if len(sys.argv) < 4:
        raise SystemExit(__doc__)

    src_path, out_path, names = sys.argv[1], sys.argv[2], sys.argv[3:]
    src = open(src_path).read()
    parts = [extract(src, n) for n in names]

    with open(out_path, "w") as f:
        f.write("/* GENERATED by tools/lift.py from %s - do not edit.\n\n" % src_path)
        f.write(NOTICE)
        f.write(" */\n")
        f.write('#include "main.h"\n\n')
        f.write("\n\n".join(parts))
        f.write("\n")

    lines = sum(len(p.splitlines()) for p in parts)
    print("lifted %s (%d lines) from %s" % (", ".join(names), lines, src_path))


if __name__ == "__main__":
    main()
