#!/usr/bin/env python3
"""Lift named functions verbatim out of a deskhop source file.

The point is that the harness runs the firmware's own code rather than a hand
copy, so a test can never quietly drift from what the device actually does.

    lift.py <source.c> <out.c> func1 [func2 ...]

Fails loudly if a function is not found, so a rename upstream breaks the build
instead of silently testing nothing.
"""
import sys


def extract(src, name):
    """Return the full text of a function definition, brace matched."""
    needle = name + "("
    pos = 0
    while True:
        i = src.find(needle, pos)
        if i == -1:
            raise SystemExit("lift.py: %s not found" % name)

        # walk back to the start of the line; skip calls and prototypes
        line_start = src.rfind("\n", 0, i) + 1
        brace = src.find("{", i)
        semi = src.find(";", i)
        if brace != -1 and (semi == -1 or brace < semi):
            break
        pos = i + len(needle)

    depth, k = 0, brace
    while True:
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return src[line_start:k + 1]


def main():
    if len(sys.argv) < 4:
        raise SystemExit(__doc__)

    src_path, out_path, names = sys.argv[1], sys.argv[2], sys.argv[3:]
    src = open(src_path).read()
    parts = [extract(src, n) for n in names]

    with open(out_path, "w") as f:
        f.write("/* GENERATED by tools/lift.py from %s - do not edit */\n" % src_path)
        f.write('#include "main.h"\n\n')
        f.write("\n\n".join(parts))
        f.write("\n")

    lines = sum(len(p.splitlines()) for p in parts)
    print("lifted %s (%d lines) from %s" % (", ".join(names), lines, src_path))


if __name__ == "__main__":
    main()
